###
GET http://localhost:8089/api/heroes/all
Accept: application/json

###
GET http://localhost:8089/api/creature/all
Accept: application/json

###
GET http://localhost:8089/api/creature/Chimera
Accept: application/json

###
GET http://localhost:8089/api/weapon/all
Accept: application/json

###
GET http://localhost:8089/api/weapon/Miecz
Accept: application/json

###
GET http://localhost:8089/api/castle/all
Accept: application/json

###
GET http://localhost:8089/api/castle/nekropolia
Accept: application/json
###
