###
http://localhost:8089/api/heroes/all
Accept: application/json

###
http://localhost:8089/api/creatures/all
Accept: application/json

###
http://localhost:8089/api/weapon/all
Accept: application/json

###
GET http://localhost:8089/api/castle/all
Accept: application/json

###
