spring:
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/Pulpit/private/heroes-game/heroes-microservice/properties/confi2
          refresh-rate: 0
          force-pull: true
  application:
    name: heroes-config-server

server:
  port: 8888




